### ISSUE TITLE
Signature verification of sgxplugin.yaml is failing - 5.8.0-rc.10

### ISSUE THREAD

**Issue by amigueldrs** [scontain/operator#24]
When running: `curl -fsSL https://raw.githubusercontent.com/scontain/SH/master/operator_controller | bash -s - --set-version 5.8.0-rc.10 --reconcile --update --secret-operator  --plugin --verbose  --username $REGISTRY_USERNAME --access-token $REGISTRY_ACCESS_TOKEN --email $REGISTRY_EMAIL`

I get aborted at
```log
- Checking SCONE Operator
- Installed version of the operator controller is '5.8.0-rc.10' and the desired version is '5.8.0-rc.10'
- Checking SGXPlugin
-   Downloading https://raw.githubusercontent.com/scontain/manifests/main/5.8.0-rc.10/sgxplugin.yaml
-   Verifying signature of https://raw.githubusercontent.com/scontain/manifests/main/5.8.0-rc.10/sgxplugin.yaml
Signature of file '.sgxplugin-manifest.template' is incorrect
```

with further investigation, I found that either the signature might be outdated
```log
+ gpg --verify --status-fd=1 --verify .sgxplugin-manifest.template.asc .sgxplugin-manifest.template
+ grep -e 'VALIDSIG 5BCAD31DCC8D5D722B7B7ABD2EBE04E7CC816D32'
```
or a public key file might be missing
`gpg --verify --status-fd=1 --verify .sgxplugin-manifest.template.asc .sgxplugin-manifest.template`
```log
[GNUPG:] NEWSIG
gpg: Signature made Mi 08 Mär 2023 09:21:59 CET
gpg:                using RSA key 5BCAD31DCC8D5D722B7B7ABD2EBE04E7CC816D32
[GNUPG:] ERRSIG 2EBE04E7CC816D32 1 10 00 1678263719 9 5BCAD31DCC8D5D722B7B7ABD2EBE04E7CC816D32
[GNUPG:] NO_PUBKEY 2EBE04E7CC816D32
gpg: Can't check signature: No public key
```
This inhibits to continue the Operator installation and the following services mesh

**Comment by scontain** [comment]
Can you try to add --trust-model always:
gpg --verify --status-fd=1 --trust-model always --verify .sgxplugin-manifest.template.asc .sgxplugin-manifest.template

We will roll this fix in release 11

**Comment by scontain** [comment]
True!  We need to add some keyring ..

**Comment by amigueldrs** [comment]
New version successfully executed: `curl -fsSL https://raw.githubusercontent.com/scontain/SH/master/operator_controller | bash -s - --reconcile --update --secret-operator  --plugin --verbose  --username $REGISTRY_USERNAME --access-token $REGISTRY_ACCESS_TOKEN --email $REGISTRY_EMAIL`
```
echo $?
0
```

**Comment by scontain** [comment]
Very good - I close the issue.
